require:
  - rubocop-minitest
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRailsVersion: 7.1
  TargetRubyVersion: 3.1
  Exclude:
    - .git/**/*
    - .github/**/*
    - bin/**/*
    - gemfiles/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*

Layout/LineLength:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
